#!/bin/bash
read -p "Praguse kuu number: " kuu
if [ $kuu -ge 3 -a $kuu -le 5 ]
then 
echo "Praegu on kevad"
elif [ $kuu -ge 6 -a $kuu -le 8 ]
then 
echo "Praegu on suvi"
elif [ $kuu -ge 9 -a $kuu -le 11 ]
then 
echo "Pragu on sügis"
elif [ $kuu -ge 12 -a $kuu -le 2 ]
then 
echo "Praegu on talv"
else 
echo "Viga..."
fi

#
