#!/bin/bash
echo -e -n "\e[1m"
read -p "Sisestage süvaline arv: " arv
ulejaak=$(($arv%2))
if [ $ulejaak == 1 ]
then
echo -e "\e[31m\e[5m$arv \e[39m\e[25mon paaritu arv"
else 
echo -e "\e[32m\e[5m$arv \e[39m\e[25mon paaris arv"
fi
echo -n -e "\e[21m"
#
