#!/bin/bash
echo "1. Unix (Sun OS)"
echo "2. Linux (Red Hat)"

read -p "Select your OS choice [1 or 2]? " osch

if [ $osch -eq 1 ]
	then
	echo "You Pick Unix (Sun OS)"
else 
	if [ $osch -eq 2 ]
	then
	echo "You pick up Liux (Red Hat)"
else 
	echo "What you don't Unix/Linux OS!?"  
  fi
fi
#
