#!/bin/bash
echo -n "Sisesta oma ees- ja perenimi: "
read eesnimi perenimi
echo "Tere tulemast, $eesnimi $perenimi"
echo " "
echo -n "Sisesat oma ees- ja perenimi: "
read eesnimi perenimi
echo "Sinu eesnimi on $eesnimi ja perenimi on $perenimi"
#
